name: object-set
env:
  CI: true

on:
  push:
  # workflow_dispatch:
  #   branches: [main]
  #   inputs:
  #     version:
  #       description: version
  #       default: patch
  #       required: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test

  # bump-version:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v1
  #     - name: bump patch version
  #       if: github.event.inputs.version == 'patch'
  #       run: npm --no-git-tag-version version patch
  #     - name: bump minor version
  #       if: github.event.inputs.version == 'minor'
  #       run: npm --no-git-tag-version version minor
  #     - name: bump major version
  #       if: github.event.inputs.version == 'major'
  #       run: npm --no-git-tag-version version major
  #     - uses: stefanzweifel/git-auto-commit-action@v4
  #       if: github.event.inputs.version == 'patch' || github.event.inputs.version == 'minor' || github.event.inputs.version == 'major'
  #       with:
  #         commit_message: "bump version"

  publish:
    name: publish
    needs:
      - test
      # - bump-version
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Push tag to GitHub if package.json version's tag is not tagged
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.PACKAGE_VERSION }}
